-- ============================================
-- 우국상 관리대장 순서 보정 (최근 접수건이 화면 맨 위로 오도록)
-- 원본 시드가 한 번의 INSERT로 들어가 전체가 같은 created_at을 가져서 순서가 원본 시트 순서 그대로였음
-- 페이지가 created_at 오름차순 정렬이므로, 시트 뒤쪽 행일수록 더 이른 created_at을 부여
-- 상호명+연락처로 원본 시드 순서와 매칭 (149건 대상, 상호명 없는 행은 제외)
-- ============================================

UPDATE woo_customers SET created_at = (NOW() - INTERVAL '1 minutes'), updated_at = (NOW() - INTERVAL '1 minutes') WHERE business_name = '광교점' AND phone = '010-2466-2156(엄마) / 010-8322-2153(딸)';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '2 minutes'), updated_at = (NOW() - INTERVAL '2 minutes') WHERE business_name = '부평해링턴점' AND phone = '010-3726-4199(실점주) / 010-4421-5300(박병민)';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '3 minutes'), updated_at = (NOW() - INTERVAL '3 minutes') WHERE business_name = '위례점' AND phone = '010-8622-3158';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '4 minutes'), updated_at = (NOW() - INTERVAL '4 minutes') WHERE business_name = '주안역점' AND phone = '010-3757-9814';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '5 minutes'), updated_at = (NOW() - INTERVAL '5 minutes') WHERE business_name = '힐스자이계양점' AND phone = '010-2729-1799';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '6 minutes'), updated_at = (NOW() - INTERVAL '6 minutes') WHERE business_name = '대구(평리점' AND phone = '010-5123-6455';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '7 minutes'), updated_at = (NOW() - INTERVAL '7 minutes') WHERE business_name = '대구(서재점)' AND phone = '010-8611-3072';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '8 minutes'), updated_at = (NOW() - INTERVAL '8 minutes') WHERE business_name = '서창점' AND phone = '010-8979-3037';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '9 minutes'), updated_at = (NOW() - INTERVAL '9 minutes') WHERE business_name = '안양비산점' AND phone = '010-3011-6185';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '10 minutes'), updated_at = (NOW() - INTERVAL '10 minutes') WHERE business_name = '파주운정(승계)' AND phone = '010-5885-8352';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '11 minutes'), updated_at = (NOW() - INTERVAL '11 minutes') WHERE business_name = '소사점' AND phone IS NULL;
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '12 minutes'), updated_at = (NOW() - INTERVAL '12 minutes') WHERE business_name = '시흥시청점' AND phone = '010-2323-9622';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '13 minutes'), updated_at = (NOW() - INTERVAL '13 minutes') WHERE business_name = '안양호계점' AND phone = '010-7110-3005';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '14 minutes'), updated_at = (NOW() - INTERVAL '14 minutes') WHERE business_name = '상일고덕점' AND phone = '010-9093-1518';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '15 minutes'), updated_at = (NOW() - INTERVAL '15 minutes') WHERE business_name = '다산신도시점' AND phone = '010-8793-4626';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '16 minutes'), updated_at = (NOW() - INTERVAL '16 minutes') WHERE business_name = '검로푸점' AND phone = '010-3199-4564';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '17 minutes'), updated_at = (NOW() - INTERVAL '17 minutes') WHERE business_name = '간석역점' AND phone = '010-4157-0579';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '18 minutes'), updated_at = (NOW() - INTERVAL '18 minutes') WHERE business_name = '글로벌캠퍼스점' AND phone = '010-8398-5543';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '19 minutes'), updated_at = (NOW() - INTERVAL '19 minutes') WHERE business_name = '녹번점' AND phone = '010-3250-6870';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '20 minutes'), updated_at = (NOW() - INTERVAL '20 minutes') WHERE business_name = '운정 해오름마을점' AND phone = '010-4089-8980';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '21 minutes'), updated_at = (NOW() - INTERVAL '21 minutes') WHERE business_name = '시흥능곡점' AND phone = '010-4195-5351';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '22 minutes'), updated_at = (NOW() - INTERVAL '22 minutes') WHERE business_name = '신원점' AND phone = '010-6357-1293';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '23 minutes'), updated_at = (NOW() - INTERVAL '23 minutes') WHERE business_name = '천왕점' AND phone = '010-7510-5001';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '24 minutes'), updated_at = (NOW() - INTERVAL '24 minutes') WHERE business_name = '매교점' AND phone = '010-9723-7896';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '25 minutes'), updated_at = (NOW() - INTERVAL '25 minutes') WHERE business_name = '신검단중앙역점' AND phone = '010-7525-7645';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '26 minutes'), updated_at = (NOW() - INTERVAL '26 minutes') WHERE business_name = '향남점' AND phone = '010-8929-7149';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '27 minutes'), updated_at = (NOW() - INTERVAL '27 minutes') WHERE business_name = '동탄점' AND phone IS NULL;
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '28 minutes'), updated_at = (NOW() - INTERVAL '28 minutes') WHERE business_name = '원흥점' AND phone IS NULL;
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '29 minutes'), updated_at = (NOW() - INTERVAL '29 minutes') WHERE business_name = '개포포레스트점' AND phone = '010-6283-0944';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '30 minutes'), updated_at = (NOW() - INTERVAL '30 minutes') WHERE business_name = '송도본점' AND phone IS NULL;
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '31 minutes'), updated_at = (NOW() - INTERVAL '31 minutes') WHERE business_name = '평촌점' AND phone = '010-2724-0954';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '32 minutes'), updated_at = (NOW() - INTERVAL '32 minutes') WHERE business_name = '달미점' AND phone = '010-5656-3683';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '33 minutes'), updated_at = (NOW() - INTERVAL '33 minutes') WHERE business_name = '광주태전점' AND phone = '010-4620-0647';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '34 minutes'), updated_at = (NOW() - INTERVAL '34 minutes') WHERE business_name = '상동점' AND phone = '010-9472-9240 / 010-4422-8999';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '35 minutes'), updated_at = (NOW() - INTERVAL '35 minutes') WHERE business_name = '동탄목동점' AND phone = '010-2905-8270';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '36 minutes'), updated_at = (NOW() - INTERVAL '36 minutes') WHERE business_name = '옥련점' AND phone = '010-2787-0205';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '37 minutes'), updated_at = (NOW() - INTERVAL '37 minutes') WHERE business_name = '포항 초곡점' AND phone = '01033341124(남편)';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '38 minutes'), updated_at = (NOW() - INTERVAL '38 minutes') WHERE business_name = '중동역점' AND phone = '010-6310-5139';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '39 minutes'), updated_at = (NOW() - INTERVAL '39 minutes') WHERE business_name = '시흥목감점' AND phone = '010-9011-5952';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '40 minutes'), updated_at = (NOW() - INTERVAL '40 minutes') WHERE business_name = '원종점' AND phone = '010-8215-6219';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '41 minutes'), updated_at = (NOW() - INTERVAL '41 minutes') WHERE business_name = '배곧한라점' AND phone = '010 2765 7743';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '42 minutes'), updated_at = (NOW() - INTERVAL '42 minutes') WHERE business_name = '북수원점' AND phone = '010-2105-5859';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '43 minutes'), updated_at = (NOW() - INTERVAL '43 minutes') WHERE business_name = '운정물향기점' AND phone = '010-9461-7055';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '44 minutes'), updated_at = (NOW() - INTERVAL '44 minutes') WHERE business_name = '덕은점' AND phone = '010-5478-6028';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '45 minutes'), updated_at = (NOW() - INTERVAL '45 minutes') WHERE business_name = '우국상수원고등점' AND phone = '010-5390-6125';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '46 minutes'), updated_at = (NOW() - INTERVAL '46 minutes') WHERE business_name = '철산점' AND phone = '010-4232-7537';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '47 minutes'), updated_at = (NOW() - INTERVAL '47 minutes') WHERE business_name = '학익시티점' AND phone = '010-7736-2324';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '48 minutes'), updated_at = (NOW() - INTERVAL '48 minutes') WHERE business_name = '봉담수영점' AND phone = '010-8881-4220';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '49 minutes'), updated_at = (NOW() - INTERVAL '49 minutes') WHERE business_name = '월곶점' AND phone = '010-4923-7773';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '50 minutes'), updated_at = (NOW() - INTERVAL '50 minutes') WHERE business_name = '중동역점(승계)' AND phone = '010-8803-1592';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '51 minutes'), updated_at = (NOW() - INTERVAL '51 minutes') WHERE business_name = '고잔신도시점' AND phone = '010-9976-1004';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '52 minutes'), updated_at = (NOW() - INTERVAL '52 minutes') WHERE business_name = '지곶점' AND phone = '010-9476-6387(배우자) / 010-7118-4630(대표)';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '53 minutes'), updated_at = (NOW() - INTERVAL '53 minutes') WHERE business_name = '소사괴안점' AND phone = '010-5219-6735';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '54 minutes'), updated_at = (NOW() - INTERVAL '54 minutes') WHERE business_name = '그랑점' AND phone = '010-4915-9661';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '55 minutes'), updated_at = (NOW() - INTERVAL '55 minutes') WHERE business_name = '영종하늘점' AND phone = '010-9152-8599';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '56 minutes'), updated_at = (NOW() - INTERVAL '56 minutes') WHERE business_name = '강남세곡점' AND phone = '010 6663 3135';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '57 minutes'), updated_at = (NOW() - INTERVAL '57 minutes') WHERE business_name = '덕이점' AND phone = '010 4926 6077';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '58 minutes'), updated_at = (NOW() - INTERVAL '58 minutes') WHERE business_name = '향동점' AND phone = '010-4015-2843';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '59 minutes'), updated_at = (NOW() - INTERVAL '59 minutes') WHERE business_name = '삼산점' AND phone = '010-8730-5311';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '60 minutes'), updated_at = (NOW() - INTERVAL '60 minutes') WHERE business_name = '수원매탄점' AND phone = '010-5406-8920';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '61 minutes'), updated_at = (NOW() - INTERVAL '61 minutes') WHERE business_name = '광교점(승계)' AND phone IS NULL;
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '62 minutes'), updated_at = (NOW() - INTERVAL '62 minutes') WHERE business_name = '도화점' AND phone = '010-7119-2941';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '63 minutes'), updated_at = (NOW() - INTERVAL '63 minutes') WHERE business_name = '진주초전점' AND phone = '010-4595-8881';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '64 minutes'), updated_at = (NOW() - INTERVAL '64 minutes') WHERE business_name = '강일점' AND phone = '1087889188(개인폰) / 01044940953(업무폰)';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '65 minutes'), updated_at = (NOW() - INTERVAL '65 minutes') WHERE business_name = '신길점' AND phone = '010-8995-6654';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '66 minutes'), updated_at = (NOW() - INTERVAL '66 minutes') WHERE business_name = '송도파크자이점' AND phone = '010-9434-5600';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '67 minutes'), updated_at = (NOW() - INTERVAL '67 minutes') WHERE business_name = '평내호평점' AND phone = '010-9462-9089(남편)';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '68 minutes'), updated_at = (NOW() - INTERVAL '68 minutes') WHERE business_name = '대구도남점' AND phone = '010-5123-6455';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '69 minutes'), updated_at = (NOW() - INTERVAL '69 minutes') WHERE business_name = '죽림점(통영 승계)' AND phone = '010-4585-6191';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '70 minutes'), updated_at = (NOW() - INTERVAL '70 minutes') WHERE business_name = '평리점(승계)' AND phone = '010-5123-6455';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '71 minutes'), updated_at = (NOW() - INTERVAL '71 minutes') WHERE business_name = '강릉교동점' AND phone = '010-3675-7098';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '72 minutes'), updated_at = (NOW() - INTERVAL '72 minutes') WHERE business_name = '구파발역점' AND phone = '010-4045-8999';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '73 minutes'), updated_at = (NOW() - INTERVAL '73 minutes') WHERE business_name = '학익점' AND phone = '010-5502-2879';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '74 minutes'), updated_at = (NOW() - INTERVAL '74 minutes') WHERE business_name = '대치점' AND phone = '010-4157-8089';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '75 minutes'), updated_at = (NOW() - INTERVAL '75 minutes') WHERE business_name = '별내점' AND phone = '010-3375-0366';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '76 minutes'), updated_at = (NOW() - INTERVAL '76 minutes') WHERE business_name = '목동센트럴점' AND phone = '010-3483-7112';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '77 minutes'), updated_at = (NOW() - INTERVAL '77 minutes') WHERE business_name = '봉담내리점' AND phone = '010-3194-6758';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '78 minutes'), updated_at = (NOW() - INTERVAL '78 minutes') WHERE business_name = '산성역점' AND phone = '010-5674-7444';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '79 minutes'), updated_at = (NOW() - INTERVAL '79 minutes') WHERE business_name = '구리갈매점' AND phone = '010-4529-0664';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '80 minutes'), updated_at = (NOW() - INTERVAL '80 minutes') WHERE business_name = '옥계산동점(구미)' AND phone = '010-4443-6336';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '81 minutes'), updated_at = (NOW() - INTERVAL '81 minutes') WHERE business_name = '광명뉴타운점' AND phone = '1035776839(대표) / 010-9108-6839(실점주)';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '82 minutes'), updated_at = (NOW() - INTERVAL '82 minutes') WHERE business_name = '하남미사' AND phone = '010-2885-9579';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '83 minutes'), updated_at = (NOW() - INTERVAL '83 minutes') WHERE business_name = '수지성복점' AND phone = '010-4903-4770';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '84 minutes'), updated_at = (NOW() - INTERVAL '84 minutes') WHERE business_name = '논현점' AND phone = '010-9978-2621';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '85 minutes'), updated_at = (NOW() - INTERVAL '85 minutes') WHERE business_name = '은계호반점' AND phone = '010-9875-8258';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '86 minutes'), updated_at = (NOW() - INTERVAL '86 minutes') WHERE business_name = '수지상현점' AND phone = '010-8967-7353';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '87 minutes'), updated_at = (NOW() - INTERVAL '87 minutes') WHERE business_name = '마곡점' AND phone = '010-2646-9154';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '88 minutes'), updated_at = (NOW() - INTERVAL '88 minutes') WHERE business_name = '충주방서점' AND phone = '010-8399-2705';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '89 minutes'), updated_at = (NOW() - INTERVAL '89 minutes') WHERE business_name = '강릉유천점' AND phone = '010-3255-7042';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '90 minutes'), updated_at = (NOW() - INTERVAL '90 minutes') WHERE business_name = '장곡점' AND phone = '010-8332-3454';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '91 minutes'), updated_at = (NOW() - INTERVAL '91 minutes') WHERE business_name = '성남도촌점' AND phone = '010-2541-9800';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '92 minutes'), updated_at = (NOW() - INTERVAL '92 minutes') WHERE business_name = '둔포중앙점' AND phone = '010-4059-8443';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '93 minutes'), updated_at = (NOW() - INTERVAL '93 minutes') WHERE business_name = '수원탑동점' AND phone = '010-5214-3822';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '94 minutes'), updated_at = (NOW() - INTERVAL '94 minutes') WHERE business_name = '과천점' AND phone = '010-8736-1346';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '95 minutes'), updated_at = (NOW() - INTERVAL '95 minutes') WHERE business_name = '초롱꽃마을점' AND phone = '010-4497-0700 / 010-7188-8292(남편)';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '96 minutes'), updated_at = (NOW() - INTERVAL '96 minutes') WHERE business_name = '청라점' AND phone = '010-9450-5052';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '97 minutes'), updated_at = (NOW() - INTERVAL '97 minutes') WHERE business_name = '옥계현진점' AND phone = '010-3823-1589';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '98 minutes'), updated_at = (NOW() - INTERVAL '98 minutes') WHERE business_name = '별하람점' AND phone = '010-8891-8933';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '99 minutes'), updated_at = (NOW() - INTERVAL '99 minutes') WHERE business_name = '용인흥덕점' AND phone = '010-9939-6317';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '100 minutes'), updated_at = (NOW() - INTERVAL '100 minutes') WHERE business_name = '광교호수점' AND phone = '010-8409-3850';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '101 minutes'), updated_at = (NOW() - INTERVAL '101 minutes') WHERE business_name = '일산 식사점' AND phone = '010-5135-7357(실점주) / 010-7573-4273(대표)';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '102 minutes'), updated_at = (NOW() - INTERVAL '102 minutes') WHERE business_name = '김천혁신점' AND phone = '010-9496-3574';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '103 minutes'), updated_at = (NOW() - INTERVAL '103 minutes') WHERE business_name = '송산점' AND phone = '010-7634-8432';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '104 minutes'), updated_at = (NOW() - INTERVAL '104 minutes') WHERE business_name = '청라라임점' AND phone = '010-5688-2137';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '105 minutes'), updated_at = (NOW() - INTERVAL '105 minutes') WHERE business_name = '구미원평점' AND phone = '010-2541-7200';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '106 minutes'), updated_at = (NOW() - INTERVAL '106 minutes') WHERE business_name = '도덕공원점' AND phone = '010-3243-1095';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '107 minutes'), updated_at = (NOW() - INTERVAL '107 minutes') WHERE business_name = '미사하남고점' AND phone = '010-6380-8149';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '108 minutes'), updated_at = (NOW() - INTERVAL '108 minutes') WHERE business_name = '테크노점' AND phone = '010-4145-6179';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '109 minutes'), updated_at = (NOW() - INTERVAL '109 minutes') WHERE business_name = '도남점' AND phone = '010-7405-0829';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '110 minutes'), updated_at = (NOW() - INTERVAL '110 minutes') WHERE business_name = '학익점' AND phone = '010-3322-7316';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '111 minutes'), updated_at = (NOW() - INTERVAL '111 minutes') WHERE business_name = '주식회사 우리마을 유니티' AND phone = '010-5172-0117';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '112 minutes'), updated_at = (NOW() - INTERVAL '112 minutes') WHERE business_name = '향남점' AND phone = '010-9975-0009';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '113 minutes'), updated_at = (NOW() - INTERVAL '113 minutes') WHERE business_name = '인덕원점' AND phone = '010-8628-3127';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '114 minutes'), updated_at = (NOW() - INTERVAL '114 minutes') WHERE business_name = '우국상 경산중산점' AND phone = '010-9071-0773';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '115 minutes'), updated_at = (NOW() - INTERVAL '115 minutes') WHERE business_name = '달성공원점' AND phone = '010-2229-0131';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '116 minutes'), updated_at = (NOW() - INTERVAL '116 minutes') WHERE business_name = '다사점' AND phone = '010-8410-7712';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '117 minutes'), updated_at = (NOW() - INTERVAL '117 minutes') WHERE business_name = '영등포점' AND phone = '010-5206-5551';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '118 minutes'), updated_at = (NOW() - INTERVAL '118 minutes') WHERE business_name = '논현지웰점' AND phone = '010-3513-7961';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '119 minutes'), updated_at = (NOW() - INTERVAL '119 minutes') WHERE business_name = '검로푸점' AND phone = '010-9931-9749 / 010-9413-5709(실점주)';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '120 minutes'), updated_at = (NOW() - INTERVAL '120 minutes') WHERE business_name = '광명일직동점' AND phone = '010-8266-1349';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '121 minutes'), updated_at = (NOW() - INTERVAL '121 minutes') WHERE business_name = '수색점' AND phone = '010-9001-6615';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '122 minutes'), updated_at = (NOW() - INTERVAL '122 minutes') WHERE business_name = '수원당수점' AND phone = '010-4444-0357 / 010-8048-0904(매장)';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '123 minutes'), updated_at = (NOW() - INTERVAL '123 minutes') WHERE business_name = '풍동점' AND phone = '010-2239-0180';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '124 minutes'), updated_at = (NOW() - INTERVAL '124 minutes') WHERE business_name = '본오점' AND phone = '010-4079-9461';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '125 minutes'), updated_at = (NOW() - INTERVAL '125 minutes') WHERE business_name = '항동점' AND phone = '010-4715-5067 / 010-2492-4424(매장)';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '126 minutes'), updated_at = (NOW() - INTERVAL '126 minutes') WHERE business_name = '화서점' AND phone = '010-4314-9656 공동대표 010-9298-5017 010-4314-9656 업무폰';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '127 minutes'), updated_at = (NOW() - INTERVAL '127 minutes') WHERE business_name = '장위점' AND phone = '010-3239-4338';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '128 minutes'), updated_at = (NOW() - INTERVAL '128 minutes') WHERE business_name = '구미옥계(옥계현진)' AND phone = '010-3255-6975';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '129 minutes'), updated_at = (NOW() - INTERVAL '129 minutes') WHERE business_name = '부평더샵점' AND phone = '010-3602-2369 매장번호 010-6289-5796';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '130 minutes'), updated_at = (NOW() - INTERVAL '130 minutes') WHERE business_name = '김천부곡점' AND phone = '010-3579-9692';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '131 minutes'), updated_at = (NOW() - INTERVAL '131 minutes') WHERE business_name = '동탄능동점' AND phone = '010-8368-5805';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '132 minutes'), updated_at = (NOW() - INTERVAL '132 minutes') WHERE business_name = '복현점' AND phone = '010-6359-0995 매장번호 010-5149-9933';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '133 minutes'), updated_at = (NOW() - INTERVAL '133 minutes') WHERE business_name = '동춘점' AND phone = '010-9688-5700';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '134 minutes'), updated_at = (NOW() - INTERVAL '134 minutes') WHERE business_name = '대구남산점' AND phone = '010-4323-2552';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '135 minutes'), updated_at = (NOW() - INTERVAL '135 minutes') WHERE business_name = '산곤청천점' AND phone = '010-9030-9958';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '136 minutes'), updated_at = (NOW() - INTERVAL '136 minutes') WHERE business_name = '동탄나루점' AND phone = '010-9365-2772';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '137 minutes'), updated_at = (NOW() - INTERVAL '137 minutes') WHERE business_name = '부천체육관점' AND phone = '010-3359-7917';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '138 minutes'), updated_at = (NOW() - INTERVAL '138 minutes') WHERE business_name = '매교권선점' AND phone = '010-7918-5369';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '139 minutes'), updated_at = (NOW() - INTERVAL '139 minutes') WHERE business_name = '한빛점' AND phone = '010-4726-7644';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '140 minutes'), updated_at = (NOW() - INTERVAL '140 minutes') WHERE business_name = '배곧한라점' AND phone = '010-4145-7331';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '141 minutes'), updated_at = (NOW() - INTERVAL '141 minutes') WHERE business_name = '호수공원서연점' AND phone = '010-6704-7445';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '142 minutes'), updated_at = (NOW() - INTERVAL '142 minutes') WHERE business_name = '신길보라매점' AND phone = '010-2034-3196';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '143 minutes'), updated_at = (NOW() - INTERVAL '143 minutes') WHERE business_name = '역북점' AND phone = '010-5496-8810';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '144 minutes'), updated_at = (NOW() - INTERVAL '144 minutes') WHERE business_name = '이문점' AND phone = '010-7231-7687';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '145 minutes'), updated_at = (NOW() - INTERVAL '145 minutes') WHERE business_name = '동탄목동점' AND phone = '010-8011-4073';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '146 minutes'), updated_at = (NOW() - INTERVAL '146 minutes') WHERE business_name = '응암역점' AND phone = '010-3501-7897';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '147 minutes'), updated_at = (NOW() - INTERVAL '147 minutes') WHERE business_name = '도량점' AND phone = '010-4663-8284';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '148 minutes'), updated_at = (NOW() - INTERVAL '148 minutes') WHERE business_name = '궁동점' AND phone = '010-5257-4251';
UPDATE woo_customers SET created_at = (NOW() - INTERVAL '149 minutes'), updated_at = (NOW() - INTERVAL '149 minutes') WHERE business_name = '조양점' AND phone = '010-9984-7516';
